<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Clean\Core\Models\CleanClient;

class CleanClientsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = [
            [
                'company_name' => 'Hotel Presidente Intercontinental',
                'contact_name' => 'María González Herrera',
                'contact_email' => 'maria.gonzalez@hotelpresident.com.mx',
                'contact_phone' => '+52 55 5327 7700',
                'secondary_phone' => '+52 55 5327 7701',
                'tax_id' => 'HPI830215ABC',
                'address' => 'Campos Elíseos 218, Polanco V Sección',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '11560',
                'country' => 'México',
                'website' => 'https://mexico.intercontinental.com',
                'industry_type' => 'hospitality',
                'client_type' => 'corporate',
                'credit_limit' => 250000.00,
                'payment_terms' => 30,
                'discount_percentage' => 15.00,
                'is_active' => true,
                'notes' => 'Cliente premium con múltiples propiedades. Requiere productos de alta calidad y certificación ecológica.',
                'acquisition_date' => '2020-03-15',
                'last_purchase_date' => '2024-07-10',
                'total_purchases' => 180500.00,
                'preferred_contact_method' => 'email',
                'delivery_instructions' => 'Entrega en dock de servicio, horario: 6:00-14:00. Contactar 30 min antes.',
                'account_manager' => 'Carlos Mendoza',
                'risk_level' => 'low',
                'certifications_required' => ['ISO 14001', 'Green Seal'],
                'cleaning_frequency' => 'daily',
                'facility_size' => 35000,
                'number_of_employees' => 450
            ],
            [
                'company_name' => 'Hospital ABC Santa Fe',
                'contact_name' => 'Dr. Roberto Sánchez Villareal',
                'contact_email' => 'roberto.sanchez@abchospital.com',
                'contact_phone' => '+52 55 1103 1600',
                'tax_id' => 'HSF920418DEF',
                'address' => 'Sur 136 No. 116, Las Américas',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '01120',
                'country' => 'México',
                'website' => 'https://www.abchospital.com',
                'industry_type' => 'healthcare',
                'client_type' => 'institution',
                'credit_limit' => 500000.00,
                'payment_terms' => 15,
                'discount_percentage' => 20.00,
                'is_active' => true,
                'notes' => 'Hospital de especialidades. Requiere productos hospitalarios certificados y desinfectantes grado médico.',
                'acquisition_date' => '2019-08-22',
                'last_purchase_date' => '2024-07-14',
                'total_purchases' => 425800.00,
                'preferred_contact_method' => 'phone',
                'delivery_instructions' => 'Acceso por entrada de servicios médicos. Documentación sanitaria requerida.',
                'account_manager' => 'Ana Patricia López',
                'risk_level' => 'low',
                'certifications_required' => ['EPA', 'FDA', 'COFEPRIS'],
                'cleaning_frequency' => 'daily',
                'facility_size' => 45000,
                'number_of_employees' => 850
            ],
            [
                'company_name' => 'Universidad Tecnológica de México',
                'contact_name' => 'Ing. Patricia Morales Castro',
                'contact_email' => 'patricia.morales@unitec.mx',
                'contact_phone' => '+52 55 5628 4000',
                'tax_id' => 'UTM851205GHI',
                'address' => 'Marina Nacional 162, Anáhuac I Sección',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '11320',
                'country' => 'México',
                'website' => 'https://www.unitec.mx',
                'industry_type' => 'education',
                'client_type' => 'institution',
                'credit_limit' => 150000.00,
                'payment_terms' => 45,
                'discount_percentage' => 12.00,
                'is_active' => true,
                'notes' => 'Universidad privada con múltiples campus. Enfoque en productos eco-amigables para áreas estudiantiles.',
                'acquisition_date' => '2021-01-10',
                'last_purchase_date' => '2024-06-28',
                'total_purchases' => 95600.00,
                'preferred_contact_method' => 'email',
                'delivery_instructions' => 'Coordinar con servicios generales. Horario de entrega: 8:00-16:00.',
                'account_manager' => 'Luis Fernando Ruiz',
                'risk_level' => 'medium',
                'certifications_required' => ['Green Seal', 'GREENGUARD'],
                'cleaning_frequency' => 'daily',
                'facility_size' => 28000,
                'number_of_employees' => 320
            ],
            [
                'company_name' => 'Corporativo Santander México',
                'contact_name' => 'Lic. Fernando Aguilar Montes',
                'contact_email' => 'fernando.aguilar@santander.com.mx',
                'contact_phone' => '+52 55 5169 4000',
                'tax_id' => 'CSM780912JKL',
                'address' => 'Prolongación Paseo de la Reforma 500, Lomas de Santa Fe',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '01219',
                'country' => 'México',
                'website' => 'https://www.santander.com.mx',
                'industry_type' => 'office',
                'client_type' => 'corporate',
                'credit_limit' => 300000.00,
                'payment_terms' => 30,
                'discount_percentage' => 18.00,
                'is_active' => true,
                'notes' => 'Corporativo bancario. Altos estándares de limpieza y presentación en áreas públicas.',
                'acquisition_date' => '2020-11-05',
                'last_purchase_date' => '2024-07-12',
                'total_purchases' => 312400.00,
                'preferred_contact_method' => 'email',
                'delivery_instructions' => 'Torre principal, nivel -1. Requiere identificación y registro de visitantes.',
                'account_manager' => 'Sandra Elizabeth Vargas',
                'risk_level' => 'low',
                'certifications_required' => ['ISO 9001', 'LEED'],
                'cleaning_frequency' => 'daily',
                'facility_size' => 42000,
                'number_of_employees' => 1200
            ],
            [
                'company_name' => 'Liverpool Insurgentes',
                'contact_name' => 'Gerardo Ramírez Cordero',
                'contact_email' => 'gerardo.ramirez@liverpool.com.mx',
                'contact_phone' => '+52 55 9178 4700',
                'tax_id' => 'LIV650824MNO',
                'address' => 'Av. Insurgentes Sur 1310, Del Valle',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '03100',
                'country' => 'México',
                'website' => 'https://www.liverpool.com.mx',
                'industry_type' => 'retail',
                'client_type' => 'corporate',
                'credit_limit' => 200000.00,
                'payment_terms' => 45,
                'discount_percentage' => 10.00,
                'is_active' => true,
                'notes' => 'Tienda departamental de lujo. Requiere productos especializados para diferentes superficies y áreas.',
                'acquisition_date' => '2021-05-18',
                'last_purchase_date' => '2024-07-08',
                'total_purchases' => 158900.00,
                'preferred_contact_method' => 'whatsapp',
                'delivery_instructions' => 'Andén de carga trasero. Horario nocturno preferible: 22:00-6:00.',
                'account_manager' => 'Miguel Ángel Torres',
                'risk_level' => 'medium',
                'certifications_required' => ['GREENGUARD', 'Cradle to Cradle'],
                'cleaning_frequency' => 'daily',
                'facility_size' => 25000,
                'number_of_employees' => 380
            ],
            [
                'company_name' => 'Restaurante Pujol',
                'contact_name' => 'Chef Enrique Olvera',
                'contact_email' => 'administracion@pujol.com.mx',
                'contact_phone' => '+52 55 5545 4111',
                'tax_id' => 'RPJ040315PQR',
                'address' => 'Tennyson 133, Polanco IV Sección',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '11550',
                'country' => 'México',
                'website' => 'https://www.pujol.com.mx',
                'industry_type' => 'restaurant',
                'client_type' => 'small_business',
                'credit_limit' => 75000.00,
                'payment_terms' => 15,
                'discount_percentage' => 8.00,
                'is_active' => true,
                'notes' => 'Restaurante de alta cocina. Productos especializados para área de cocina y comensales.',
                'acquisition_date' => '2022-03-12',
                'last_purchase_date' => '2024-07-15',
                'total_purchases' => 68500.00,
                'preferred_contact_method' => 'phone',
                'delivery_instructions' => 'Entrada de servicio lateral. Coordinar con chef ejecutivo.',
                'account_manager' => 'Roberto Carlos Jiménez',
                'risk_level' => 'medium',
                'certifications_required' => ['NSF', 'USDA Organic'],
                'cleaning_frequency' => 'daily',
                'facility_size' => 800,
                'number_of_employees' => 45
            ],
            [
                'company_name' => 'Grupo Bimbo Planta Azcapotzalco',
                'contact_name' => 'Ing. Laura Beatriz Hernández',
                'contact_email' => 'laura.hernandez@grupobimbo.com',
                'contact_phone' => '+52 55 5268 6600',
                'tax_id' => 'GBA440214STU',
                'address' => 'Prolongación Paseo de la Reforma 1000, Peña Blanca Santa Fe',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '01210',
                'country' => 'México',
                'website' => 'https://www.grupobimbo.com',
                'industry_type' => 'manufacturing',
                'client_type' => 'corporate',
                'credit_limit' => 400000.00,
                'payment_terms' => 30,
                'discount_percentage' => 22.00,
                'is_active' => true,
                'notes' => 'Planta de producción alimentaria. Requiere productos grado alimentario y certificaciones estrictas.',
                'acquisition_date' => '2019-06-08',
                'last_purchase_date' => '2024-07-13',
                'total_purchases' => 520800.00,
                'preferred_contact_method' => 'email',
                'delivery_instructions' => 'Dock 3 - Área de químicos. Requiere MSDS y certificados de calidad.',
                'account_manager' => 'Andrea Sofía Ramírez',
                'risk_level' => 'low',
                'certifications_required' => ['FDA', 'HACCP', 'SQF'],
                'cleaning_frequency' => 'daily',
                'facility_size' => 65000,
                'number_of_employees' => 890
            ],
            [
                'company_name' => 'Secretaría de Salud CDMX',
                'contact_name' => 'Lic. Mónica Liliana Rangel',
                'contact_email' => 'monica.rangel@salud.cdmx.gob.mx',
                'contact_phone' => '+52 55 5132 1200',
                'tax_id' => 'SSC850930VWX',
                'address' => 'Donceles 39, Centro Histórico',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '06010',
                'country' => 'México',
                'industry_type' => 'government',
                'client_type' => 'government',
                'credit_limit' => 180000.00,
                'payment_terms' => 60,
                'discount_percentage' => 5.00,
                'is_active' => true,
                'notes' => 'Dependencia gubernamental. Proceso de licitación requerido. Facturación con requisitos fiscales específicos.',
                'acquisition_date' => '2021-09-15',
                'last_purchase_date' => '2024-05-20',
                'total_purchases' => 98600.00,
                'preferred_contact_method' => 'email',
                'delivery_instructions' => 'Oficialía de partes. Documentación oficial requerida para ingreso.',
                'account_manager' => 'Jorge Alberto Castillo',
                'risk_level' => 'high',
                'certifications_required' => ['COFEPRIS', 'NOM-002-SSA1'],
                'cleaning_frequency' => 'daily',
                'facility_size' => 15000,
                'number_of_employees' => 280
            ],
            [
                'company_name' => 'Limpieza Profesional del Centro S.A.',
                'contact_name' => 'Guadalupe Moreno Silva',
                'contact_email' => 'guadalupe.moreno@limpiezapro.com.mx',
                'contact_phone' => '+52 55 5542 8890',
                'tax_id' => 'LPC190812YZ1',
                'address' => 'Eje Central Lázaro Cárdenas 13, Centro',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '06050',
                'country' => 'México',
                'industry_type' => 'other',
                'client_type' => 'small_business',
                'credit_limit' => 50000.00,
                'payment_terms' => 30,
                'discount_percentage' => 12.00,
                'is_active' => false,
                'notes' => 'Empresa de servicios de limpieza. Cliente inactivo por falta de pagos puntuales.',
                'acquisition_date' => '2022-11-03',
                'last_purchase_date' => '2024-02-14',
                'total_purchases' => 28900.00,
                'preferred_contact_method' => 'phone',
                'delivery_instructions' => 'Bodega en planta baja. Horario: 9:00-17:00.',
                'account_manager' => 'Pedro Antonio Mendoza',
                'risk_level' => 'high',
                'certifications_required' => [],
                'cleaning_frequency' => 'weekly',
                'facility_size' => 500,
                'number_of_employees' => 12
            ],
            [
                'company_name' => 'Centro Comercial Santa Fe',
                'contact_name' => 'Arq. Ricardo Salinas Domínguez',
                'contact_email' => 'ricardo.salinas@centrosantafe.com.mx',
                'contact_phone' => '+52 55 1105 7300',
                'tax_id' => 'CCS971020AB2',
                'address' => 'Av. Vasco de Quiroga 3800, Santa Fe',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '01210',
                'country' => 'México',
                'website' => 'https://www.centrosantafe.com.mx',
                'industry_type' => 'retail',
                'client_type' => 'corporate',
                'credit_limit' => 350000.00,
                'payment_terms' => 30,
                'discount_percentage' => 16.00,
                'is_active' => true,
                'notes' => 'Centro comercial premium. Requiere productos para múltiples superficies y alto tráfico de personas.',
                'acquisition_date' => '2020-07-25',
                'last_purchase_date' => '2024-07-11',
                'total_purchases' => 285400.00,
                'preferred_contact_method' => 'email',
                'delivery_instructions' => 'Área de servicios nivel B2. Coordinar con administración 24hrs antes.',
                'account_manager' => 'Carmen Rosa Delgado',
                'risk_level' => 'low',
                'certifications_required' => ['LEED', 'BREEAM'],
                'cleaning_frequency' => 'daily',
                'facility_size' => 85000,
                'number_of_employees' => 150
            ]
        ];

        foreach ($clients as $clientData) {
            CleanClient::create($clientData);
        }
    }
}